version: 1.2

workflows:
  - name: magma-annotate
    subclass: WDL
    primaryDescriptorPath: /magma-annotate.wdl
    authors:
      - name: "Yu-Han Hsu"
        email: "yuhahsu@broadinstitute.org"

